Pin Pillow version to <10.0.0
`Pillow` 10.0.0 appears to trigger the following error, pinning to lower until resolved

```python
"AttributeError: 'FreeTypeFont' object has no attribute 'getsize'" and missing expected files
```